language: java

services:
  - docker

matrix:
  fast_finish: true
  include:
    - os: linux
      dist: trusty
      jdk: openjdk8
      sudo: required
      addons:
        apt:
          packages:
            - docker-ce
    - os: linux
      #dist: trusty
      jdk: openjdk11
      sudo: required



before_install:
  - git clone https://github.com/GIP-RECIA/docker-mariadb.git && cd docker-mariadb
  - docker-compose pull && docker-compose build
  - docker-compose up -d
  - mysql -h 127.17.0.1 -u root -proot -e "create database publisher_test DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;"
  - cd .. && git clone https://github.com/GIP-RECIA/docker-openldap-test.git && cd docker-openldap-test
  - docker-compose pull && docker-compose build
  - docker-compose up -d
  - docker ps -a

script:
  - ./mvnw clean generate-sources
  - ./mvnw compile liquibase:update
  - ./mvnw test -Dspring.profiles.active=test
